[package]
name = "ublacklist-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
dialoguer = "0.11.0"
regex = "1.11.1"
toml = "0.8.19"

[dependencies.serde]
version = "1.0.200"
features = ["derive"]
