# A

# B
[[rule]]
domain = "sixapart.jp"

[[rule]]
domain = "bugsfighter.com"

# C

# D
[[rule]]
domain = "docker.jp"
comment = "2024/12/12: 長い間 v24.0 のままで最新版への追随も行っているようだが，公式ドキュメントで十分なので削除"

[[rule]]
domain = "good-f-design.com"

# E
# F
# G
# H
# I
# J
[[rule]]
domain = "linux-console.net"

[[rule]]
domain = "linux-terminal.com"

# K
# L

# M
[[rule]]
domain = "misskey-hub.net"

[[rule]]
domain = "misskey.io"
comment = "2024/12/12: ドメインブロック中のインスタンス"

[[rule]]
domain = "misskey.flowers"
comment = "2024/12/29: ドメインブロック中"

# N
# O
# P
# Q
# R
# S
# T
[[rule]]
domain = "twitter.com"

[[rule]]
domain = "codecamp.jp"

# U
# V

# W
[[rule]]
domain = "webdesign-trends.net"

# X
[[rule]]
domain = "x.com"

# Y
# Z
