# A

# B
[[rule]]
domain = "sixapart.jp"

# C

# D
[[rule]]
domain = "docker.jp"
comment = "2024/12/12: 長い間 v24.0 のままで最新版への追随も行っているようだが，公式ドキュメントで十分なので削除"

[[rule]]
domain = "good-f-design.com"
comment = "2024/12/12: なんか 403 を吐く．なんでブロックしたのか忘れたが，まあこのままで"

# E
# F
# G
# H
# I
# J
# K
# L
# M
[[rule]]
domain = "misskey.io"
comment = "2024/12/12: Misskey って調べただけで出てくるの鬱陶しい．求めてない"

# N
# O
# P
# Q
# R
# S
# T
[[rule]]
domain = "twitter.com"
comment = "2024/12/12: 有害 (x.com にリダイレクトされるため不要だと思われるが，インデックスが残っている可能性があるため)"

# U
# V

# W
[[rule]]
domain = "webdesign-trends.net"
comment = "2024/12/12: 必要ない"

# X
[[rule]]
domain = "x.com"
comment = "2024/12/12: 有害"

# Y
# Z
